API_project/API_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v2/', include('api_v2.urls')),

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

API_project/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from accounts.views import register_view, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'account'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name ='registration'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'detail'),
    path('change/', UserChangeView.as_view(), name ='user_change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name = 'password_change')
    ]

API_project/api_v2/urls.py
from django.urls import include, path
from rest_framework import routers

from api_v2.views import ArticleViewSet

router = routers.DefaultRouter()
# router.register(r'orders', OrderViewSet)
router.register(r'articles', ArticleViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

API_project/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from django.db import models
status_choice = [('moderate', 'модерированная'), ('new', 'новая')]
# Create your models here.
class Article(models.Model):
    text = models.TextField(max_length=2000, null=False, blank=False, verbose_name='Цитата', validators=(MinLengthValidator(5),))
    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=100, blank=False, null=False, verbose_name='почтовый адрес')
    rating = models.IntegerField(verbose_name='rate', null=False, blank=False, default=0)
    status = models.CharField(max_length=50, null=False, choices=status_choice,  blank=False, default='новая')
    data = models.DateTimeField(auto_now_add=True, verbose_name='время добавления')


    class Meta:
        db_table = 'article'
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
class RateArticle(models.Model):
    article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE, related_name='rate_article',
                                verbose_name='Статья', null=False, blank=False)
    rate = models.IntegerField(blank=False, null=False, verbose_name='Рейтинг', validators=[MinValueValidator(-1), MaxValueValidator(1)])
    class Meta:
        db_table = 'rate_article'
        verbose_name = 'rate'
        verbose_name_plural = 'rates'

    def __str__(self):
        return f'{self.article}: {self.user}'


# class DeRateArticle(models.Model):
#     article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE, related_name='like_article',
#                                 verbose_name='Статья', null=False, blank=False)
#     user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='user_rate_article')
#
#     class Meta:
#         db_table = 'rate_article'
#         verbose_name = 'rate'
#         verbose_name_plural = 'rates'
#
#     def __str__(self):
#         return f'{self.article}: {self.user}'

API_project/webapp/forms.py
from django import forms
from webapp.models import Goods, Review


class Goodform(forms.ModelForm):
    class Meta:
        model=Goods
        fields=('name', 'description', 'category', 'image')


class GoodDeleteForm(forms.Form):
    name=forms.CharField(max_length=100, required=True, label='Введите название товара чтобы удалить его')



class SimpleSearchForm(forms.Form):

    search = forms.CharField(max_length=100, required=False, label="Найти")


class ReviewForms(forms.ModelForm):

    class Meta:
        model=Review
        fields = ['text_review', 'rating']


class ModerateForm(forms.ModelForm):

    class Meta:
        model=Review
        fields = ['text_review', 'rating', 'moderation']

API_project/webapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Добро пожаловать{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>


    <div class="container">
    <nav class="navbar">
        <ul class="menu">

            <li>
                <a href="{% url "main_page" %}"> На главную</a>
            </li>
{#            <li>#}
{#                <a href="{% url 'project_more' %}">Задачи</a>#}
{#            </li>#}
            {% include 'partial/navigation.html' %}

            {% if user.is_authenticated %}
                {% block menu %}{% endblock %}
                <li class="'menu-right"><a href="{% url 'account:logout' %}?next = {{ request.get_full_path }}" class="nav-link">Выход</a></li>
                <li class="'menu-right"> Привет {{ user.username }}!</li>
                 <li class="'menu-right"><a href="{% url 'account:detail' request.user.id %}?next = {{ request.get_full_path }}" class="nav-link">Профиль</a></li>
            {% else %}
                <li class="'menu-right"><a href="{% url 'account:login' %}?next = {{ request.get_full_path }}" class="nav-link">Вход</a></li>
                <li class="'menu-right"><a href="{% url 'account:registration' %}?next = {{ request.get_full_path }}" class="nav-link">Регистрация</a></li>
            {% endif %}


        </ul>
    </nav>

        <h1>{% block page_header %}Добро пожаловать!!!!{% endblock page_header %}</h1>
        {% block content %}{% endblock content %}
    </div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>