API_project/API_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v2/', include('api_v2.urls')),

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

API_project/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from accounts.views import register_view, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'account'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name ='registration'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'detail'),
    path('change/', UserChangeView.as_view(), name ='user_change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name = 'password_change')
    ]

API_project/api_v2/urls.py
from django.urls import include, path
from rest_framework import routers

from api_v2.views import ArticleViewSet

router = routers.DefaultRouter()
# router.register(r'orders', OrderViewSet)
router.register(r'articles', ArticleViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

API_project/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, verbose_name='Профиль пользователя', related_name='profile')
    birth_date = models.DateField(
        null=True, blank=True, verbose_name='Дата рождения'
    )
    image = models.ImageField(upload_to='images', null=True, blank=True)
    about_me = models.TextField(null=True, blank=True, verbose_name='О себе', max_length=2000)
    github = models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub', max_length=300)


    def __str__(self):
        return self.user.username


    class Meta:
        db_table = 'profiles'
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'
        permissions = [('view_users', 'просмотр пользователей')]

API_project/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import Profile


class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.EmailField(label='Почтовый адресс', required=True)
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise ValidationError('Заполните хотя бы одно поле first_name или last_name!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']




class UserChangeForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label='Новый пароль', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label='Старый пароль', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm  = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password !=password_confirm:
            raise forms.ValidationError('Пароли не совпадают')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        print(self.instance)
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit = True):
        user = self.instance
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

API_project/accounts/views.py
# from django.contrib.auth import authenticate, login, logout
# from django.shortcuts import render, redirect,
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse

from django.views.generic import DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm



def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()

            login(request, user)
            return redirect('main_page')
    else:
        form = MyUserCreationForm()
    return render(request, 'registration/user_create.html', context={'form': form})


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        # projects = self.get_object().projects.all()
        # paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        # page_number = self.request.GET.get('page', 1)
        # page = paginator.get_page(page_number)
        # kwargs['page_obj'] = page
        # kwargs['projects'] = page.object_list
        # kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)

    def get_object(self, queryset=None):
        return self.request.user

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES

        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('account:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('account:detail', kwargs={'pk': self.request.user.pk})

API_project/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %} Редактировать пользователя {% endblock %}
{% block menu_links %}
<li><a href="{% url 'account:detail' user_obj.pk %}">Назад</a></li>
<li><a href="">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'account:user_change' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% include 'partial/base_form.html' with fields_only=True %}
    {% include 'partial/base_form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

API_project/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}

{% block content %}
    {% block menu_links %}
        {% if request.user == user_obj %}
        <li><a href="{% url 'account:user_change' %}">Редактировать!!!</a></li>
        <li><a href="{% url 'account:password_change' user_obj.pk %}">Смена пароля</a></li>
        {% endif %}
    {% endblock %}

    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.image %}
        <img class="avatar" src="{{ user_obj.profile.image.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    {% if user_obj.profile.github %}
        <p><a href="{{ user_obj.profile.github }}">Ссылка на гитхаб: </a></p>
    {% endif %}

    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
    <p>Почта: {{ user_obj.email }}</p>
    <p>О себе: {{ user_obj.profile.about_me }}</p>
    <h2 class="text-center clear">Статьи автора:</h2>
    {{ user_obj.review.all }}
{#    {% include 'partial/project_list.html' %}#}
{% endblock %}

API_project/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %} Смена пароля {% endblock %}
{% block menu_links %}
{#    <li>#}
{#    <a href="{% url 'account:detail' %}">Назад</a>#}
{#    </li>#}
    <li><a href="{% url 'account:user_change' %}"> Редактирование личных данных!!!</a></li>
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
{#    {% url 'account:password_change' user_obj.pk as action_url%}#}
    <form action="" method="post">
    {% include 'partial/base_form.html' with button_text='change' %}
    </form>



{% endblock %}


{#{% block menu %}#}
{#    <li><a href="{% url 'account:detail' request.user.pk%}">Назад</a></li>#}
{#    <li><a href="{% url 'account:user_change' %}"> Редактировать личных данных</a></li>#}
{#{% endblock %}#}